os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode8
install:
  - bash TestRedis/install_redis_local.sh
script:
  - export PATH="$PWD/redis-stable/src/:$PATH"
  - make redis-start
  - swift build
  - swift test
notifications:
  email:
    on_success: never
    on_failure: change